title: <p align="center"> Nishant Singh </p>
logo: /assets/img/photo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nishant-singh-4b3647166/">LinkedIn</a> |
  <a href="https://github.com/nishantswo">GitHub</a>
  
  <br>   
  I'm working on Data Science, Cloud Machine learning & NLP related problems.
  Working in Cloud Industry for 8 years.
  <br>
  </p>



theme: jekyll-theme-minimal
